name: Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  UV_VERSION: "0.6.6"

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@f94ec6bedd8674c4426838e6b50417d36b6ab231 # v5.3.1
        with:
          version: "${{ env.UV_VERSION }}"
          enable-cache: true
          cache-dependency-glob: uv.lock

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version-file: pyproject.toml

      - name: Install dependencies
        run: |-
          uv sync --all-extras --all-groups --locked
          echo "$(pwd)/.venv/bin" >> $GITHUB_PATH

      - name: Run lint
        run: |-
          ruff check . --output-format=github
          ruff format . --check

  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@f94ec6bedd8674c4426838e6b50417d36b6ab231 # v5.3.1
        with:
          version: "${{ env.UV_VERSION }}"
          enable-cache: true
          cache-dependency-glob: uv.lock

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version-file: pyproject.toml

      - name: Install dependencies
        run: |-
          uv sync --all-extras --all-groups --locked
          echo "$(pwd)/.venv/bin" >> $GITHUB_PATH

      - name: Run tests
        run: |-
          python -m pytest
